version: '2'

services:

  jupyter:
    image: jayjohnson/jupyter:2.0.5
    container_name: "jupyter"
    hostname: "jupyter"
    env_file: 
      - ./test/jupyter.env
    ports:
      - "82:8888"
    volumes:
      - .:/opt/work
    network_mode: "host"

